import { Tour } from 'nextstepjs';

export const onboadingTour: Tour[] = [
  {
    tour: 'onboardingTour',
    steps: [
      {
        icon: '👋',
        title: 'Welcome to QReview Setup!',
        content: "Let's get your business set up and generate your first review QR code in under two minutes.",
        selector: '#tour-welcome',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        disableInteraction: true,
      },
      {
        icon: '📝',
        title: 'Business Details',
        content: 'Enter your business name, contact email, category, and location to build your profile.',
        selector: '#tour-business-form',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '🔗',
        title: 'Google Business URL',
        content: 'Paste your Google Business review link here. This is where your QR code will direct customers.',
        selector: '#tour-google-url',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '🚀',
        title: 'Launch Status',
        content: 'Track your setup progress here. Once you submit, we will generate your QR poster instantly.',
        selector: '#tour-progress',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '📱',
        title: 'QR Poster Preview',
        content: 'Your customized QR poster will appear here. After generation, we will redirect you to your dashboard!',
        selector: '#tour-qr-preview',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '✨',
        title: 'Create Your Setup',
        content: 'Click here when you are ready to create your business and generate the QR code.',
        selector: '#tour-submit',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
    ],
  },
];