import { Tour } from 'nextstepjs';

export const tourSteps: Tour[] = [
  {
    tour: 'dashboardTour',
    steps: [
      {
        icon: '👋',
        title: 'Welcome to QReview Dashboard!',
        content: "Let's take a quick tour to help you get started with managing your business reviews and generating QR codes.",
        selector: '#tour-welcome',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        disableInteraction: true,
      },
      {
        icon: '🏢',
        title: 'Select Your Business',
        content: 'Use this dropdown to switch between different business locations and view their specific data, reviews, and QR codes.',
        selector: '#business-selector',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '📊',
        title: 'Key Metrics at a Glance',
        content: 'Track your total businesses, reviews, average rating, and active reviews in real-time. These metrics update automatically.',
        selector: '#stats-grid',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '⭐',
        title: 'Rating Distribution',
        content: 'See how your reviews are distributed across different star ratings. The green bar shows your positive review percentage.',
        selector: '#rating-distribution',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '📱',
        title: 'QR Marketing Toolkit',
        content: 'Generate professional QR codes for your business. Customers can scan these to leave reviews instantly.',
        selector: '#qr-toolkit',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '🔗',
        title: 'Share Your Review Link',
        content: 'Copy your unique review link and share it with customers via email, social media, or anywhere else.',
        selector: '#copy-link',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '⚡',
        title: 'Quick Actions',
        content: 'Access key features like viewing all reviews, customizing your QR codes, and managing settings.',
        selector: '#quick-actions',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '🎉',
        title: "You're All Set!",
        content: "You're ready to start collecting and managing reviews. Remember, you can always restart this tour from the header.",
        selector: '#tour-complete',
        side: 'top',
        showControls: true,
        showSkip: true,
        disableInteraction: true,
      },
    ],
  },
   {
    tour: 'onboardingTour',
    steps: [
      {
        icon: '👋',
        title: 'Welcome to QReview Setup!',
        content: "Let's get your business set up and generate your first review QR code in under two minutes.",
        selector: '#tour-welcome',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        disableInteraction: true,
      },
      {
        icon: '📝',
        title: 'Business Details',
        content: 'Enter your business name, contact email, category, and location to build your profile.',
        selector: '#tour-business-form',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '🔗',
        title: 'Google Business URL',
        content: 'Paste your Google Business review link here. This is where your QR code will direct customers.',
        selector: '#tour-google-url',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '🚀',
        title: 'Launch Status',
        content: 'Track your setup progress here. Once you submit, we will generate your QR poster instantly.',
        selector: '#tour-progress',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '📱',
        title: 'QR Poster Preview',
        content: 'Your customized QR poster will appear here. After generation, we will redirect you to your dashboard!',
        selector: '#tour-qr-preview',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '✨',
        title: 'Create Your Setup',
        content: 'Click here when you are ready to create your business and generate the QR code.',
        selector: '#tour-submit',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
    ],
  },
];